### ISSUE TITLE
possible demo bug on useDark page 

### ISSUE THREAD

**Issue by yikayiyo** [vueuse/vueuse#1300]
## Possible Bug

After click the button, there is some style bug.
<img width="389" alt="image" src="https://user-images.githubusercontent.com/22975826/154878365-abe9a837-506f-4022-864b-d2c5f9299d3b.png">
I clone the project and run it in the **local environment**, it just **works fine**.
I inspect the console log, and here it is
```
app.a53fcaf6.js:1 Hydration completed but contains mismatches.
c @ app.a53fcaf6.js:1
workbox-b7e829be.js:1 Uncaught (in promise) non-precached-url: non-precached-url :: [{"url":"index.html"}]
    at E.createHandlerBoundToURL (https://vueuse.org/workbox-b7e829be.js:1:13196)
    at Object.createHandlerBoundToURL (https://vueuse.org/workbox-b7e829be.js:1:14779)
    at https://vueuse.org/sw.js:1:31097
    at https://vueuse.org/sw.js:1:565
```
Could it be a SSR side effect? Or is it caused by my slow network condition?

## Code

The [demo code](https://github.com/vueuse/vueuse/blob/main/packages/core/useDark/demo.vue) 
```
<button @click="toggleDark()">
    <carbon-moon v-show="isDark" class="align-middle" />
    <carbon-sun v-show="!isDark" class="align-middle" />
    <span class="ml-2">{{ isDark ? 'Dark': 'Light' }}</span>
</button>
```
When toggle the button, some css like `display: inline-block;` doen't apply to the svg element. Was this related to `unplugin-vue-components`? By the way, `align-middle` looks like it could be replaced by `inline-block`.
If this is a bug, What should I learn before fix it?

**Comment by yikayiyo** [comment]
More infomation: The first time you visit the page, everything works fine. After a refresh, this bug will show. 
And I don't think this is related to 'v-show'.
