### ISSUE TITLE
useStorage breaking web component build

### ISSUE THREAD

**Issue by ericuldall** [vueuse/vueuse#3456]
### Describe the bug

I'm using `useStorage` in a web component build. And it's causing some errors when built for production. It works fine in dev mode but when I build the dist and run it in my browser I get the following error:
```
vue-widget.js:1147 TypeError: el.addEventListener is not a function
    at addEventListener (vue-widget.js:5105:6)
    at register (vue-widget.js:5589:8)
    at vue-widget.js:5601:46
    at Array.map (<anonymous>)
    at vue-widget.js:5601:28
    at Array.flatMap (<anonymous>)
    at watch.immediate (vue-widget.js:5600:19)
    at callWithErrorHandling (vue-widget.js:1093:18)
    at callWithAsyncErrorHandling (vue-widget.js:1101:17)
    at job (vue-widget.js:1687:9)
````

I've already built a dist and you can just open `dist/test.html` (https://github.com/ericuldall/vuese-breaks-webcomponent/blob/main/dist/test.html) in the reproduction repo to see the bug immediately. Error does not happen if I remove useStorage.

### Reproduction

https://github.com/ericuldall/vuese-breaks-webcomponent

### System Info

```Shell
Macos, built for browser

build config:

import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'

export default defineConfig({
  plugins: [vue()],
  build: {
    lib: {
      entry: './src/main.ts',
      name: 'vue-widget',
      fileName: 'vue-widget',
      formats: ['es']
    },
    minify: false
  },
  define: {
    'process.env': {
      NODE_ENV: 'production'
    }
  }
})
```
```


### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vueuse/vueuse/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vueuse/vueuse/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vueuse.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/vueuse/vueuse/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a VueUse issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vueuse/vueuse/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ericuldall** [comment]
So not sure this is directly related to vueuse... the error goes away as well if I build as IIFE. So it seems there may be some interplay with other code on the page that was causing the issue. closing for now.
