### ISSUE TITLE
'effectScope' is not exported by vue-demi/lib/index.mjs

### ISSUE THREAD

**Issue by eratio08** [vueuse/vueuse#686]
I'm facing the following issue when trying to build a project with vite `2.4.3` using vueuse `6.0.0`. 

```
'effectScope' is not exported by node_modules/@vueuse/core/node_modules/vue-demi/lib/index.mjs, imported by node_modules/@vueuse/core/node_modules/@vueuse/shared/index.esm.js
file: .../node_modules/@vueuse/core/node_modules/@vueuse/shared/index.esm.js:1:64
1: import { computed, unref, watch, ref, customRef, isVue3, isRef, effectScope, onScopeDispose, reactive, toRef, isVue2, toRefs as toRefs$1, getCurrentInstance, onMounted, nextTick, getCurrentScope, onUnmounted } from 'vue-demi';
                                                                   ^
2: 
3: /**
error during build:
Error: 'effectScope' is not exported by node_modules/@vueuse/core/node_modules/vue-demi/lib/index.mjs, imported by node_modules/@vueuse/core/node_modules/@vueuse/shared/index.esm.js
    at error (/Users/eikelurz/src/fi-perdix/frontend/node_modules/rollup/dist/shared/rollup.js:151:30)
    at Module.error (/Users/eikelurz/src/fi-perdix/frontend/node_modules/rollup/dist/shared/rollup.js:10044:16)
    at Module.traceVariable (/Users/eikelurz/src/fi-perdix/frontend/node_modules/rollup/dist/shared/rollup.js:10429:29)
    at ModuleScope.findVariable (/Users/eikelurz/src/fi-perdix/frontend/node_modules/rollup/dist/shared/rollup.js:9200:39)
    at FunctionScope.findVariable (/Users/eikelurz/src/fi-perdix/frontend/node_modules/rollup/dist/shared/rollup.js:3635:38)
    at ChildScope.findVariable (/Users/eikelurz/src/fi-perdix/frontend/node_modules/rollup/dist/shared/rollup.js:3635:38)
    at Identifier.bind (/Users/eikelurz/src/fi-perdix/frontend/node_modules/rollup/dist/shared/rollup.js:4572:40)
    at CallExpression.bind (/Users/eikelurz/src/fi-perdix/frontend/node_modules/rollup/dist/shared/rollup.js:2886:23)
    at CallExpression.bind (/Users/eikelurz/src/fi-perdix/frontend/node_modules/rollup/dist/shared/rollup.js:7133:15)
    at VariableDeclarator.bind (/Users/eikelurz/src/fi-perdix/frontend/node_modules/rollup/dist/shared/rollup.js:2886:23)
```

**Comment by antfu** [comment]
> From v6.0, VueUse requires vue >= v3.2 or @vue/composition-api >= v1.1

**Comment by FRSgit** [comment]
Does it mean that from v6.0 vueuse is not meant to work with vue^2?
