### ISSUE TITLE
`useRouteQuery` is broken on Vue 2

### ISSUE THREAD

**Issue by aantn** [vueuse/vueuse#902]
It relies on `useRoute` which doesn't exist.

**Comment by webfansplz** [comment]
the route option has been exposed，you can set it to $route

**Comment by antfu** [comment]
@vueuse/router does not support Vue 2 as documented.

**Comment by aantn** [comment]
I've tried to work around this by using https://github.com/ambit-tsai/vue2-helpers/issues/2 which implements `useRoute` and `useRouter`. I understand that @vueuse/router doesn't support Vue 2, but it would still be nice if there was a workaround for this.

Everything seems to work but the following error appears frequently in the console:

```
vue-router.esm.js?8c4f:2065 Uncaught (in promise) NavigationDuplicated: Avoided redundant navigation to current location: "/".
    at createRouterError (webpack-internal:///./node_modules/vue-router/dist/vue-router.esm.js:2066:15)
    at createNavigationDuplicatedError (webpack-internal:///./node_modules/vue-router/dist/vue-router.esm.js:2036:15)
    at HTML5History.confirmTransition (webpack-internal:///./node_modules/vue-router/dist/vue-router.esm.js:2329:18)
    at HTML5History.transitionTo (webpack-internal:///./node_modules/vue-router/dist/vue-router.esm.js:2261:8)
    at HTML5History.replace (webpack-internal:///./node_modules/vue-router/dist/vue-router.esm.js:2614:10)
    at eval (webpack-internal:///./node_modules/vue-router/dist/vue-router.esm.js:3040:22)
    at new Promise (<anonymous>)
    at VueRouter.replace (webpack-internal:///./node_modules/vue-router/dist/vue-router.esm.js:3039:12)
    at eval (webpack-internal:///./node_modules/@vueuse/router/index.mjs:64:77)
    at Array.eval (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:1988:12)
```

Is this an issue with vue2-helpers that I should discuss with @ambit-tsai
